### ISSUE TITLE
Las imágenes de la página de las tareas iniciales son muy grandes

### ISSUE THREAD

**Issue by AdrianBZG** [alu0100845235/tareas-iniciales-alu0100845235#3]
Deberían estar redimensionadas para que sean más pequeñas
:smile:

**Comment by alu0100845235** [comment]
Ya está resuelto :sweat_smile:.

Para poder redimensionar las imágenes y que se viera correctamente en GitHub no he podido hacerlo directamente con Markdown usando ![](image/atom1.png =300x), he tenido que usar que usar **líneas de html dentro del index.md.**

_Actualizado tanto en la rama gh-pages como en la master._

Gracias.
